### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by ResolutePSD** [The-Coding-Academy/coding-bot-v4#10]
**Describe the bug**
The last line 507, "    bot.run(bot.token)" is where there is an error with an Attribute Error with the mention of 'NoneType' object has no attribute 'strip'.

**Expected behavior**
I don't really know haha

**Screenshots**
![Screen Shot 2021-03-11 at 11 38 55 PM](https://user-images.githubusercontent.com/78404092/110844635-122b6700-82c3-11eb-816b-03f5439999c0.png)

**Discord Version**:
Newest version, don't know what that would be but it's up to date.

**Additional context**
Everything went perfect including the setup until the execution of the bot.

**Comment by BobDotCom** [comment]
Did you run ```bash
. ./start``` in your console before running the bot?

**Comment by ResolutePSD** [comment]
> Did you run `. ./setup` in your console before running the bot?

Yes I have

**Comment by BobDotCom** [comment]
> > Did you run `. ./setup` in your console before running the bot?
> 
> Yes I have

what was the output?
