### ISSUE TITLE
Make Code Better.

### ISSUE THREAD

**Issue by ToxicKidz** [The-Coding-Academy/coding-bot-v4#8]
**Is your feature request related to a problem? Please describe.**
A lot of this code doesn't follow [PEP 8](https://www.python.org/dev/peps/pep-0008/), some lines are too long, some excessive, ect.
**Describe the solution you'd like**
I would like to make changes to the code to make it more readable.

**Comment by BobDotCom** [comment]
I already have fixed all of the files on my working tree, besides just one of them. I'm doing that one right now and it'll be committed and pushed later today. I manually fixed all of the code based off the suggestions from a flake 8 linter, so it should be good.
![Screen Shot 2021-03-05 at 7 58 58 PM](https://user-images.githubusercontent.com/71356958/110125405-e2db9e00-7d88-11eb-97b1-6a1400d47594.png)
